### ISSUE TITLE
[AWS::KMS::Key] add CFN default `aws:cloudformation:stack-name`, `aws:cloudformation:logical-id` and `aws:cloudformation:stack-id` tags

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/aws-cloudformation-resource-providers-kms#68]
### Issue Description

To find the right CloudFormation Stack, where a AWS resource is defined/maintained, **aws:cloudformation:*** built-in tags are needed. This is an important function in day-to-day business.

### Expected Behavior

Resources with type `AWS::KMS::Key`, which are managed as CloudFormations Stacks, should automatically receive the `aws:cloudformation:*` built-in tags / automatic default CFN AutoTags.

Once support <ins>CloudFormation Drift-Detection</ins> will be added via https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1671, please handled by those automatic tags correctly (hence, aws:cloudformation:* tags are _not_ a drift)

### Observed Behavior

When you have an `AWS::KMS::Key` resource in your stack, it does not get the built-in tags assigned: 
* `aws:cloudformation:stack-name`
* `aws:cloudformation:logical-id`
* `aws:cloudformation:stack-id`

### Test Cases

Example Templates: Deploy this Stack in one Region:
 
 ```
 Resources:
   EncryptionKey:
     Type: 'AWS::KMS::Key'
     Properties:
       Description: TestKeyForTags
       EnableKeyRotation: true
       MultiRegion: true
       Enabled: true
       Tags:
         - Key: "Stack Name Not Default Tag"
           Value: !Ref AWS::StackName
       KeyPolicy:
         Version: 2012-10-17
         Statement:
           - Effect: Allow
             Principal:
               AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
             Action:
               - 'kms:*'
             Resource: '*'
 ```

You will see on both Resources that aside from CloudFormation defined Tags, no other Tags are placed onto the Resources.
No tags `aws:cloudformation:*` are added to the resource (just the tags defined via Template-Resource-Level or via Stack-Level). 

### Links
* https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/2077
